### ISSUE TITLE
Add support for ImprovedHammer from BuildIt mod

### ISSUE THREAD

**Issue by Behoston** [gittywithexcitement/ValheimBuildCamera#2]
https://github.com/RockerKitten/BuildIt

![image](https://user-images.githubusercontent.com/7823689/133002178-bc04d694-ae6d-41b5-95ef-55678a8d1ea3.png)

**Comment by gittywithexcitement** [comment]
Hi, if you can tell me the name (in the code) of the hammer from that mod, I will add it for you, just like we did in this change: https://github.com/gittywithexcitement/ValheimBuildCamera/commit/0a92f35c088ab72d79ce6726cf498a74c3c1ecab

**Comment by RockerKitten** [comment]
the m_name is $ImprovedHammer the prefab ID is rk_hammer

**Comment by gittywithexcitement** [comment]
Thanks @RockerKitten . Added!

**Comment by gittywithexcitement** [comment]
FYI I am unable to test as I don't have the ImprovedHammer mod, nor am I playing the game, so let me know if that didn't work. Get version 1.6

**Comment by Behoston** [comment]
Maybe you can extract tool list to config file? It will be ultimate
solution, each player can decide on their own which tool should work with
build camera

pon., 20 wrz 2021, 06:37 użytkownik Daniel Killebrew <
***@***.***> napisał:

**Comment by Behoston** [comment]
Works fine
