### ISSUE TITLE
Mod doesn't work after the Hearth and Home update

### ISSUE THREAD

**Issue by Kemicaloid** [gittywithexcitement/ValheimBuildCamera#3]
Mod loads but the camera gets locked in place when attempting to activate it, the log shows the following error:

`﻿[Error  : Unity Log] MissingMethodException: single ZInput.GetJoyLeftStickX()                                           Stack trace:                                                                                                            Valheim_Build_Camera.Valheim_Build_Camera.UpdateBuildCamera (System.Single dt, GameCamera& __instance) (at <cbfecd1921f642358d9148e64feb1d1a>:0)                                                                                                Valheim_Build_Camera.Valheim_Build_Camera.UpdateCamera (System.Single dt, GameCamera& __instance, System.Boolean& __runOriginal) (at <cbfecd1921f642358d9148e64feb1d1a>:0)                                                                      (wrapper dynamic-method) GameCamera.DMD<GameCamera::UpdateCamera>(GameCamera,single)                                    GameCamera.LateUpdate () (at <30933934adb94e3fa486522beec45894>:0)`

**Comment by gittywithexcitement** [comment]
I'm uploading a new version now. Thanks for the bug report. Get version 1.6
